### ISSUE TITLE
알고리즘 정리는 문제이름? 문제 번호?

### ISSUE THREAD

**Issue by wlxo0401** [imsoncod/Python-Algorithm#1]
어떻게 하는게 좋을가요

**Comment by imsoncod** [comment]
저같은 경우에는 문제의 제목을 파일명으로, 번호나 카테고리는 Commit Message로 관리하고 있습니다.
선택은 @wlxo0401 님 편하신대로 하시면 될 것 같습니다.

**Comment by wlxo0401** [comment]
- [ 굳]
